### ISSUE TITLE
Corporate Design issues and suggestions

### ISSUE THREAD

**Issue by capi3** [EnormousCloud/airnode#15]
Body

- H1 to #F3F3F3
- set bg to #000000
- set content bg to #030303
- set .table-providers th to #F3F3F3 
- set .table-providers td.stats to color: #f3f3f3; font-size: 1em;

Footer

- replace box shadow with a white line
- set the footer content to the width of the content div box

**Comment by EnormousCloud** [comment]
Thank for the feedback

Please check other screens as well inside each provider, I believe there are still things to be commented
